### ISSUE TITLE
There should be a direct download link for app.

### ISSUE THREAD

**Issue by santosh** [Leaking/WeGit#3]
Those who don't want to compile by own and just want to try the app. 

An apk file hosted somewhere.

**Comment by Leaking** [comment]
Thx for you suggestion,I will add a module to search user and reposiroty and release an apk.quickly.i will finish it in this week.

**Comment by santosh** [comment]
Okay, nice! I'm closing this issue. :)

**Comment by Leaking** [comment]
Hello,Now you can download a newest apk from [here](https://github.com/Leaking/WeGit/raw/master/screenshot/wegit_v0.5.apk)
