### ISSUE TITLE
Don't leave password field naked.

### ISSUE THREAD

**Issue by santosh** [Leaking/WeGit#5]
When logging into app, entering password should feel like it. I mean it currently shows it as plain ascii.

**Comment by Leaking** [comment]
I 'd fixid it.Thx ^_^ 
I close this issue now.thx

**Comment by santosh** [comment]
Can you link to the commited line in file? :)

**Comment by Leaking** [comment]
Do you meet this ?https://github.com/Leaking/WeGit/commit/808ee5d61a6a8cfc6bdd852e076886bfa4593a85

you can find i add this simple line:
```Java
    android:inputType="textPassword"
```
